//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("University.App.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutPageAboutUs {
            get {
                return ResourceManager.GetString("AboutPageAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Us.
        /// </summary>
        public static string AboutPageMeetUs {
            get {
                return ResourceManager.GetString("AboutPageMeetUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string AboutPageSeeMore {
            get {
                return ResourceManager.GetString("AboutPageSeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Password.
        /// </summary>
        public static string ChangedPassword {
            get {
                return ResourceManager.GetString("ChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was changed successfully.
        /// </summary>
        public static string ChangedPasswordSuccessfully {
            get {
                return ResourceManager.GetString("ChangedPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed the password.
        /// </summary>
        public static string ChangedThePassword {
            get {
                return ResourceManager.GetString("ChangedThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields are required.
        /// </summary>
        public static string FieldsRequired {
            get {
                return ResourceManager.GetString("FieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Sign Up.
        /// </summary>
        public static string LoginPageDontHaveAccount {
            get {
                return ResourceManager.GetString("LoginPageDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or member from here to access.
        /// </summary>
        public static string LoginPageLoginMember {
            get {
                return ResourceManager.GetString("LoginPageLoginMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuPageAbout {
            get {
                return ResourceManager.GetString("MenuPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Password.
        /// </summary>
        public static string MenuPageChangedPassword {
            get {
                return ResourceManager.GetString("MenuPageChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string MenuPageLogOut {
            get {
                return ResourceManager.GetString("MenuPageLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MenuPageProfile {
            get {
                return ResourceManager.GetString("MenuPageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable.
        /// </summary>
        public static string PQRSAcceptable {
            get {
                return ResourceManager.GetString("PQRSAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string PQRSBad {
            get {
                return ResourceManager.GetString("PQRSBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string PQRSClaim {
            get {
                return ResourceManager.GetString("PQRSClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complain.
        /// </summary>
        public static string PQRSComplain {
            get {
                return ResourceManager.GetString("PQRSComplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string PQRSExcellent {
            get {
                return ResourceManager.GetString("PQRSExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string PQRSPageDirection {
            get {
                return ResourceManager.GetString("PQRSPageDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PQRSPageEmail {
            get {
                return ResourceManager.GetString("PQRSPageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string PQRSPageMessage {
            get {
                return ResourceManager.GetString("PQRSPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PQRSPageName {
            get {
                return ResourceManager.GetString("PQRSPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PQRSPagePhone {
            get {
                return ResourceManager.GetString("PQRSPagePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate our service.
        /// </summary>
        public static string PQRSPageRateOurSevice {
            get {
                return ResourceManager.GetString("PQRSPageRateOurSevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string PQRSPageSend {
            get {
                return ResourceManager.GetString("PQRSPageSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string PQRSPageSurname {
            get {
                return ResourceManager.GetString("PQRSPageSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of request.
        /// </summary>
        public static string PQRSPageTypeOfRequest {
            get {
                return ResourceManager.GetString("PQRSPageTypeOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petition.
        /// </summary>
        public static string PQRSPetition {
            get {
                return ResourceManager.GetString("PQRSPetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string PQRSRegular {
            get {
                return ResourceManager.GetString("PQRSRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string PQRSSuggestion {
            get {
                return ResourceManager.GetString("PQRSSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well.
        /// </summary>
        public static string PQRSWell {
            get {
                return ResourceManager.GetString("PQRSWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing in.
        /// </summary>
        public static string RegisterPageSingIn {
            get {
                return ResourceManager.GetString("RegisterPageSingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register successfull.
        /// </summary>
        public static string RegisterSuccessfull {
            get {
                return ResourceManager.GetString("RegisterSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save password.
        /// </summary>
        public static string SavePassword {
            get {
                return ResourceManager.GetString("SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type of request.
        /// </summary>
        public static string SelectTypeRequest {
            get {
                return ResourceManager.GetString("SelectTypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a new picture.
        /// </summary>
        public static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process is successfull.
        /// </summary>
        public static string TheProcessSuccessfull {
            get {
                return ResourceManager.GetString("TheProcessSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you going to take the photo?.
        /// </summary>
        public static string WhereTakePhoto {
            get {
                return ResourceManager.GetString("WhereTakePhoto", resourceCulture);
            }
        }
    }
}
